spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees(?<segment>/?.*), /api/v1/employees${segment}

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments(?<segment>/?.*), /api/v1/departments${segment}

        # Add project service route for bonus section
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects(?<segment>/?.*), /api/v1/projects${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG