spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.dir}/config-repo
  profiles:
    active: native

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
