spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees(?<segment>/?.*), /api/v1/employees${segment}
            - AddRequestHeader=X-API-Version, v1

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments(?<segment>/?.*), /api/v1/departments${segment}
            - AddRequestHeader=X-API-Version, v1

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products(?<segment>/?.*), /api/v1/products${segment}
            - AddRequestHeader=X-API-Version, v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG