logging:
  level:
    org.springframework.cloud: INFO
    com.example: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics

feature:
  flags:
    enable-audit: true
    enable-caching: true
    enable-circuit-breaker: true

api:
  version:
    current: v1
    deprecated: []
    supported: [v1]