spring:
  redis:
    host: localhost
    port: 6379

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

fakestore:
  api:
    base-url: https://fakestoreapi.com
    timeout: 5000

logging:
  level:
    com.example.product